#!/bin/bash

if [ "$1" = "start" ]; then
	sudo udatapath/ofdatapath --datapath-id=b4b52fd06906 --interfaces=eth0,eth1 ptcp:6635& 
fi

if [ "$1" = "open" ]; then
	utilities/dpctl tcp:ubuntu:6635 flow-mod table=0,cmd=add ,in_port=1, apply:output=2
	utilities/dpctl tcp:ubuntu:6635 flow-mod table=0,cmd=add ,in_port=2, apply:output=1
fi

if [ "$1" = "stats" ]; then
	utilities/dpctl tcp:ubuntu:6635 stats-flow table=0
fi

if [ "$1" = "open_bundle" ]; then
	utilities/dpctl tcp:ubuntu:6635 bundle open -b 4
fi

if [ "$1" = "add" ]; then
	utilities/dpctl -4 2 tcp:ubuntu:6635 flow-mod table=0,cmd=add ,in_port=1, apply:output=2
fi

if [ "$1" = "commit" ]; then
utilities/dpctl tcp:ubuntu:6635 bundle commit -b 2
fi







